### ISSUE TITLE
关于小程序测试时，提示网络异常

### ISSUE THREAD

**Issue by gftvlie** [ossso/wxapp_one#1]
用开发工具测试时，页面可以正常访问获取数据。但是选择预览，通过微信二维码查看时，则提示网络异常，首页无法加载出内容。
![image](https://user-images.githubusercontent.com/13698534/41917742-9f4b33b4-798d-11e8-8511-d1575a72e29a.png)

![image](https://user-images.githubusercontent.com/13698534/41917861-c202d3da-798d-11e8-8ade-298a7d9fad8b.png)

![image](https://user-images.githubusercontent.com/13698534/41917880-c7106c0c-798d-11e8-85e2-c91a035030ab.png)

可能需要辛苦抽空帮忙看下。

我是根据这个页面里的流程执行的 https://www.os369.com/article/3

**Comment by ossso** [comment]
小程序后台配置服务器域名，格式例如 ： https://www.os369.com   即可 

教程是被写坑了一些。。。

**Comment by gftvlie** [comment]
@ossso 介不介意给个私人联系方式，再进一步沟通哇。老乡，俺也是四川的
